#!/groups/scheffer/home/plaza/cluster_build/bin python

import drmaa
import sys

s = drmma.Session()
jt = s.createJobTemplate()
jt = remoteCommand("calclabels_cluster")
jt.args = [sys.argv[1]]

# ?! set environment for run

# run on only one slot ??
s.runJob(jt)


